package com.xs.chat.ui

import androidx.compose.runtime.staticCompositionLocalOf

/** 当前界面语言（zh / en），由 MainActivity 提供。 */
val LocalLanguage = staticCompositionLocalOf { "zh" }

/** 轻量 i18n：主界面常用文案中英对照，缺失时回退中文。 */
object Lang {
    fun t(lang: String, key: String): String {
        val table = if (lang == "en") EN else ZH
        return table[key] ?: ZH[key] ?: key
    }

    private val ZH = mapOf(
        "new_chat" to "新对话",
        "history" to "对话记录",
        "edit_history" to "编辑会话",
        "edit_conversation" to "编辑会话",
        "rename_conversation" to "编辑会话",
        "select_all" to "全选",
        "cancel" to "取消",
        "save" to "保存",
        "pin" to "置顶",
        "unpin" to "取消置顶",
        "delete" to "删除",
        "delete_selected" to "删除所选",
        "messages_count" to "%d 条消息",
        "empty_conversation" to "（空对话）",
        "settings" to "设置",
        "back" to "返回",
        "send" to "发送",
        "stop" to "停止",
        "add" to "添加",
        "image" to "图片",
        "file" to "文件",
        "video" to "视频",
        "ai_image" to "AI 生图（图生图/文生图）",
        "ai_video" to "AI 生视频（图生视频/文生视频）",
        "ai_edit_file" to "AI 修改文件",
        "input_placeholder" to "给 XS Chat 发送消息…",
        "input_placeholder_no_model" to "请先配置模型",
        "thinking" to "思考中…",
        "edit_message" to "编辑消息",
        "translate_message" to "翻译消息",
        "share_message" to "分享消息",
        "copy" to "复制",
        "regenerate" to "重新生成",
        "remove_attachment" to "移除附件",
        "current_model" to "当前模型：%s",
        "select_model" to "选择模型",
        "switch_model" to "切换模型",
        "no_model" to "当前未配置模型",
        "go_add_model" to "去设置添加模型",
        "welcome_title" to "XS Chat",
        "welcome_tagline" to "兼容 OpenAI API 的多模型 AI 聊天客户端",
        "welcome_features" to "支持 Markdown、代码高亮、流式输出、历史会话",
        "model_sheet_title" to "选择模型",
        "load_from_server" to "加载模型",
        "manage_models" to "管理模型",
        "default_mark" to "默认",
        "api_settings" to "API 设置",
        "my_models" to "我的模型",
        "appearance" to "外观",
        "language" to "语言",
        "about" to "关于",
        "follow_system" to "跟随系统",
        "light_mode" to "浅色模式",
        "dark_mode" to "深色模式",
        "model_count" to "共 %d 个模型",
        "no_models_hint" to "暂无模型。点击上方「从所有已保存 API 加载模型」自动导入，或手动添加。",
        "temp_label" to "Temperature：%s",
        "system_prompt" to "System Prompt（可选）",
        "load_models_btn" to "从所有已保存 API 加载模型",
        "models_loaded" to "加载成功：新增 %d 个模型",
        "models_fresh" to "模型已是最新，未发现新模型",
        "api_key" to "API Key",
        "streaming_dot" to "▍",
        "call_stats" to "⬆ %s ⬇ %s · %.1fs",
        "call_more" to " ×%d 次",
        "expand_all" to "展开全部（%d）",
        "collapse" to "收起",
        "saved_apis" to "已保存的 API",
        "select_saved_api" to "选择已保存的 API",
        "save_current_api" to "保存当前 API",
        "api_name_hint" to "API 名称（如 OpenAI / DeepSeek）",
        "use_api" to "使用",
        "plugin_prompt_title" to "%s",
        "plugin_prompt_hint_image" to "描述你想生成的图片（可结合已添加的参考图做图生图）…",
        "plugin_prompt_hint_video" to "描述视频内容（可结合已添加的参考图做图生视频）…",
        "plugin_prompt_hint_file" to "描述你想如何修改已添加的文本文件…",
        "generate" to "生成",
        "ok" to "确定",
        "api_need_base_url" to "请先填写 Base URL",
        "video_need_ref" to "提示：未添加参考图片时将执行文生视频",
        "file_need_ref" to "提示：需先在输入框上方添加一个文本文件",
        "no_apis_hint" to "暂无已保存的 API，可在上方填写 Base URL / API Key 后保存",
        "media_settings" to "媒体生成参数",
        "image_pixel" to "图片像素",
        "video_resolution" to "视频分辨率",
        "video_duration" to "视频时长",
        "select_param" to "选择",
        "confirm_change" to "确认更改",
        "saved_ok" to "已保存",
        "seconds_suffix" to "秒",
        "media_param_invalid" to "格式无效：像素/分辨率需 WxH（如 1024x1024），视频分辨率可选 720P/960P/2K，时长需 1-18 的整数秒",
        "mic" to "麦克风",
        "voice_call" to "实时语音通话",
        "video_call" to "实时视频通话",
        "call_end" to "挂断",
        "memory" to "操作记忆",
        "memory_count" to "共 %d 条",
        "memory_empty" to "暂无操作记录",
        "memory_clear" to "清空",
        "memory_clear_done" to "已清空操作记忆",
        "memory_limit" to "记忆上限（条）",
        "memory_limit_invalid" to "请输入大于 0 的数字",
        "call_role" to "通话互动角色",
        "call_role_add" to "新增角色",
        "call_role_name" to "角色名称",
        "call_role_voice" to "音色（TTS voice）",
        "call_role_dialect" to "方言/腔调",
        "call_role_prompt" to "人设提示词（可选）",
        "call_dialing" to "正在呼叫 %s…",
        "call_connected" to "已接听",
        "call_switch_camera" to "切换摄像头",
        "call_listening" to "聆听中…",
        "call_recognizing" to "识别中…",
        "call_thinking" to "AI 思考中…",
        "call_reply_playing" to "AI 回复中…",
        "call_muted" to "已静音",
        "call_unmuted" to "已取消静音",
        "call_model_loading" to "正在加载离线语音模型…",
        "mic_recording" to "录音中，等待说话…",
        "call_voice_unavailable" to "语音识别不可用：%s",
        "call_tts_unavailable" to "语音合成不可用：%s",
        "call_role_image" to "选择形象",
        "call_role_image_selected" to "已选择形象",
        "call_role_speed" to "语速",
        "jump_to_latest" to "跳转到最新消息"
    )

    private val EN = mapOf(
        "new_chat" to "New Chat",
        "history" to "Chat History",
        "edit_history" to "Edit History",
        "edit_conversation" to "Edit Conversation",
        "rename_conversation" to "Rename Conversation",
        "select_all" to "Select All",
        "cancel" to "Cancel",
        "save" to "Save",
        "pin" to "Pin",
        "unpin" to "Unpin",
        "delete" to "Delete",
        "delete_selected" to "Delete Selected",
        "messages_count" to "%d messages",
        "empty_conversation" to "(empty)",
        "settings" to "Settings",
        "back" to "Back",
        "send" to "Send",
        "stop" to "Stop",
        "add" to "Add",
        "image" to "Image",
        "file" to "File",
        "video" to "Video",
        "ai_image" to "AI Image (image-to-image / text-to-image)",
        "ai_video" to "AI Video (image/text-to-video)",
        "ai_edit_file" to "AI Edit File",
        "input_placeholder" to "Message XS Chat…",
        "input_placeholder_no_model" to "Configure a model first",
        "thinking" to "Thinking…",
        "edit_message" to "Edit Message",
        "translate_message" to "Translate",
        "share_message" to "Share",
        "copy" to "Copy",
        "regenerate" to "Regenerate",
        "remove_attachment" to "Remove attachment",
        "current_model" to "Current model: %s",
        "select_model" to "Select Model",
        "switch_model" to "Switch Model",
        "no_model" to "No model configured",
        "go_add_model" to "Add model in Settings",
        "welcome_title" to "XS Chat",
        "welcome_tagline" to "Multi-model AI chat client compatible with the OpenAI API",
        "welcome_features" to "Markdown, code highlighting, streaming output, chat history",
        "model_sheet_title" to "Select Model",
        "load_from_server" to "Load Models",
        "manage_models" to "Manage Models",
        "default_mark" to "Default",
        "api_settings" to "API Settings",
        "my_models" to "My Models",
        "appearance" to "Appearance",
        "language" to "Language",
        "about" to "About",
        "follow_system" to "Follow System",
        "light_mode" to "Light Mode",
        "dark_mode" to "Dark Mode",
        "model_count" to "%d models",
        "no_models_hint" to "No models yet. Tap the load button above to import, or add manually.",
        "temp_label" to "Temperature: %s",
        "system_prompt" to "System Prompt (optional)",
        "load_models_btn" to "Load models from all saved APIs",
        "models_loaded" to "Loaded %d new models",
        "models_fresh" to "Models are up to date",
        "api_key" to "API Key",
        "streaming_dot" to "",
        "call_stats" to "↑ %s ↓ %s · %.1fs",
        "call_more" to " ×%d calls",
        "expand_all" to "Show all (%d)",
        "collapse" to "Collapse",
        "saved_apis" to "Saved APIs",
        "select_saved_api" to "Select saved API",
        "save_current_api" to "Save current API",
        "api_name_hint" to "API name (e.g. OpenAI / DeepSeek)",
        "use_api" to "Use",
        "plugin_prompt_title" to "%s",
        "plugin_prompt_hint_image" to "Describe the image to generate (can use attached reference image)…",
        "plugin_prompt_hint_video" to "Describe the video (can use attached reference image)…",
        "plugin_prompt_hint_file" to "Describe how to modify the attached text file…",
        "generate" to "Generate",
        "ok" to "OK",
        "api_need_base_url" to "Please fill in Base URL first",
        "video_need_ref" to "Note: text-to-video will run without a reference image",
        "file_need_ref" to "Note: attach a text file first",
        "no_apis_hint" to "No saved APIs. Fill in Base URL / API Key above and save.",
        "media_settings" to "Media Settings",
        "image_pixel" to "Image Size",
        "video_resolution" to "Video Resolution",
        "video_duration" to "Video Duration",
        "select_param" to "Select",
        "confirm_change" to "Apply",
        "saved_ok" to "Saved",
        "seconds_suffix" to "s",
        "media_param_invalid" to "Invalid format: pixel/resolution as WxH (e.g. 1024x1024), video size 720P/960P/2K, duration 1-18 seconds",
        "mic" to "Mic",
        "voice_call" to "Voice Call",
        "video_call" to "Video Call",
        "call_end" to "Hang Up",
        "memory" to "Memory Log",
        "memory_count" to "%d entries",
        "memory_empty" to "No operation records yet",
        "memory_clear" to "Clear",
        "memory_clear_done" to "Memory cleared",
        "memory_limit" to "Memory limit (entries)",
        "memory_limit_invalid" to "Enter a number greater than 0",
        "call_role" to "Call Role",
        "call_role_add" to "Add Role",
        "call_role_name" to "Name",
        "call_role_voice" to "Voice (TTS)",
        "call_role_dialect" to "Dialect",
        "call_role_prompt" to "Persona (optional)",
        "call_dialing" to "Calling %s…",
        "call_connected" to "Connected",
        "call_switch_camera" to "Switch camera",
        "call_listening" to "Listening…",
        "call_recognizing" to "Recognizing…",
        "call_thinking" to "AI thinking…",
        "call_muted" to "Muted",
        "call_unmuted" to "Unmuted",
        "call_model_loading" to "Loading offline model…",
        "mic_recording" to "Recording, listening…",
        "call_voice_unavailable" to "Speech recognition unavailable: %s",
        "call_tts_unavailable" to "TTS unavailable: %s",
        "call_role_image" to "Choose image",
        "call_role_image_selected" to "Image selected",
        "call_role_speed" to "Speech Rate",
        "jump_to_latest" to "Jump to latest"
    )
}






